FROM php:8.2-apache

RUN docker-php-ext-install pdo pdo_mysql

COPY ./index.php /var/www/html/index.php
COPY ./api.php /var/www/html/api.php
COPY ./assets /var/www/html/assets
COPY ./classes /var/www/classes

RUN chown -R www-data:www-data /var/www/html

RUN a2enmod rewrite

EXPOSE 80